### ISSUE TITLE
Is this crate crosscompiled easily ?

### ISSUE THREAD

**Issue by gbip** [antoyo/relm#19]
Hello,
I would like to know if I can easily make a gui application for windows on linux with this crate ?
Thanks !

**Comment by karan-ta** [comment]
+1

i think this depends on if gtk can be cross compiled ?

i have same question.

**Comment by antoyo** [comment]
Would you only need this feature to release versions of your software for Windows?
If yes, you could [deploy versions from AppVeyor](https://www.appveyor.com/docs/deployment/github/).

If no, this would be more an issue for gtk-rs to be crossed-compiled, I believe.

**Comment by gbip** [comment]
I would mostly need this feature, yes.
The real question is, once it works on Linux, is it difficult to make it compile on windows ?
I will take a look at AppVeyor, thanks !

**Comment by antoyo** [comment]
Well, if you only use portable APIs, I believe it should work on Windows.
If you want example of using AppVeyor, please look at the one from [gtk-rs](https://github.com/gtk-rs/gtk/blob/master/appveyor.yml) and [relm](https://github.com/antoyo/relm/blob/master/appveyor.yml) (which is quite similar to the former).

**Comment by etrombly** [comment]
I added a tutorial for it here http://gtk-rs.org/tuto/cross, the instructions are the same for relm and gtk-rs

**Comment by antoyo** [comment]
I'm closing this issue since there's now a tutorial to cross-compile (linked in the previous post).
I'm not sure if the latest version of relm works on Windows though (I'm sure the networking code in `futures-glib` does not work on Windows even if it compiles, but `relm` does not use networking code).
If someone with Windows could check if `relm` version 0.10 works on Windows, it would be great.
