### ISSUE TITLE
Change Label font size

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#198]
How to change Label's fontsize?
There's no method I can see for setting the font or it's size.

[This page](https://www.kksou.com/php-gtk2/sample-codes/change-the-font-and-font-size-of-GtkLabel.php), for example, uses `modify_font`, but that's an old version and it doesn't exist anymore

**Comment by emmanueltouzery** [comment]
i know of two ways:

1. set markup for the label instead of plain text, then use pango markup (like <big> or things like that)

2. more flexible: use CSS. you can assign a CSS class to the label like so:

        self.header_label
            .get_style_context()
            .add_class("event_header_label");

And then set CSS for that label. You can find examples in the relm repo and projects using relm (I had lots of luck with https://github.com/sanpii/effitask ).

**Comment by MGlolenstine** [comment]
Oooh, thanks! and I was here, looking for a method call to `font_size` :sweat_smile:
