### ISSUE TITLE
notebook pages communication

### ISSUE THREAD

**Issue by whdxwym** [antoyo/relm#202]
I have a notebook with two pages, and want to read data from one page in the other page. 
I send GetMsg to the page's parent, and the parent send GetMsg to the other page, then the other page send data with a SendMsg to the parent, and the parent send it to the first page. I think this way is too complicated, and I cannot find an example to do it. Is there a better way?

**Comment by antoyo** [comment]
It is indeed the way to two this.
There's [syntax](https://github.com/antoyo/relm/blob/master/relm-examples/tests/communication-attribute.rs#L173) to make this less cumbersome.
If that's not enough, maybe you could only have one relm widgets so that you don't have to send the data between multiple relm widgets.

**Comment by whdxwym** [comment]
Ok, thank you very much. my notebook page contains too many entries to fit in one file, so I guess I have to use the old way.

**Comment by antoyo** [comment]
If that is the case, you can still create sub-modules to divide the widget in multiple files:
[that's what I did in titanium where app is divided in multiple files.](https://github.com/antoyo/titanium/tree/master/src/app)
