### ISSUE TITLE
Support or switch to Nuklear 2D GUI library

### ISSUE THREAD

**Issue by J-F-Liu** [antoyo/relm#34]
[Nuklear](https://github.com/snuk182/nuklear-rust) is an immediate mode GUI (IMGUI) library.
IMGUI is a non-retained mode of graphical interface programming, the UI is just a function of the current application state, thus the application is not responsible for explicitly managing the UI state and keeping it in sync with the app.
So IMGUI goes well with Elm architecture and able to use a single codebase for multi-platform applications.

**Comment by antoyo** [comment]
`relm` was initially written for my [web browser](https://github.com/antoyo/titanium) (which doesn't use `relm`, yet). So switching to such a backend which does not support `webkit` is not going to happen.
However, supporting different backends is an option. Currently, it should not requires too much effort to add different backends, but when `relm` will switch to using [`futures-glib`](https://github.com/antoyo/relm/issues/13), it's going to be more work to support another backend.
If you are interested to add support for this backend, please work on it. I'll be happy to answer to your questions and to explain you some parts of `relm` so that you can make it work.

**Comment by antoyo** [comment]
I'm closing this seems there does not seem that anyone started to work on such a thing yet.
Please reopen if you're interested to work on such a project.
