### ISSUE TITLE
Allow frontends other than gtk

### ISSUE THREAD

**Issue by Ppjet6** [antoyo/relm#41]
I am interested in an Elm like approach for UI in Rust but with other frontends like curses, and also maybe virtual-dom. Do you think it is possible to separate GTK from relm?

**Comment by antoyo** [comment]
Yes it is possible.
But with the new `feature/futures-glib` branch, it will be harder to use new frontends with `relm` because that would require something like [`futures-glib`](https://github.com/antoyo/futures-glib-rs) to spawn futures on the main loop of these other toolkits.
This is not in my priority, but when the aforementioned branch will be merged, I'll be happy to help anyone to make it possible.

**Comment by superlou** [comment]
@Ppjet6, are you looking for something similar to [Cedar](https://github.com/jtomschroeder/cedar)?  It's not as fully developed as Relm, but it uses a virtual-dom and intends to be front-end agnostic.  I believe both projects are shooting for a Rust-friendly, declarative style.

**Comment by antoyo** [comment]
@Ppjet6 already knows about this project (look at the issues ;) ).

**Comment by superlou** [comment]
Ah.  Good point. :)

**Comment by antoyo** [comment]
I'm closing this issue as no one seems to be working on adding support for another front-end.
If anyone is interested, please reopen the issue.
